site_name: Planimation
nav:
    - User Information:
        - Home: README.md
        - User Guide: ug1.md
    - Developer Information:
        - Deployment: deployment_guide.md
        - Backend: backend_dev_guide.md
        - Frontend: frontend_dev_guide.md
        - Animation Profile: ap_guide.md
    - Component Information:
          - Backend: backend.md
          - Frontend: frontend.md
          - Plugins: plugins.md
    - Animated Domains: https://github.com/planimation/documentation/tree/master/AnimationProfiles        
    - GitHub Code: https://github.com/planimation  
    - Contributors: contributors.md

theme:
    name: material
plugins:
    - search
    - git-revision-date-localized:
        type: date
markdown_extensions: 
    - toc:
        permalink: Link
    - codehilite